from __future__ import annotations

from client.tutorials.bootstrap import (
    board_reading_bootstrap,
    change_bootstrap,
    contested_guidance_bootstrap,
    ejection_bootstrap,
    expand_bootstrap,
    failed_expand_bootstrap,
    respawn_bootstrap,
    spoils_change_bootstrap,
    spoils_choice_bootstrap,
    spoils_expand_bootstrap,
    steal_war_bootstrap,
    trade_bootstrap,
    unguided_behavior_bootstrap,
    vagrant_guidance_bootstrap,
    war_scoring_bootstrap,
    winner_choice_bootstrap,
    worship_scoring_bootstrap,
    worship_timing_bootstrap,
)
from client.tutorials.types import (
    TutorialCompletionRule,
    TutorialHighlightSpec,
    TutorialInputGate,
    TutorialScenarioDefinition,
    TutorialStepDefinition,
)


def _rule(*event_types: str) -> TutorialCompletionRule:
    return TutorialCompletionRule(event_types=set(event_types))


def _match_event(event_type: str, key: str, value: str) -> TutorialCompletionRule:
    return TutorialCompletionRule(
        event_types={event_type},
        predicate=lambda event, scene: event.get(key) == value,
    )


def _gate_equals(action_kind: str, key: str, value: str, label: str) -> TutorialInputGate:
    return TutorialInputGate(
        allowed_actions={action_kind},
        validator=lambda action, payload, scene: (
            payload.get(key) == value,
            None if payload.get(key) == value else f"Left-click the highlighted {label}."
        ),
    )


def _gate_select_hex(kind: str, label: str) -> TutorialInputGate:
    return TutorialInputGate(
        allowed_actions={"select_hex"},
        validator=lambda action, payload, scene: (
            payload.get("kind") == kind,
            None if payload.get("kind") == kind else f"Left-click one of the highlighted {label}."
        ),
    )


BASICS_SCENARIOS = [
    TutorialScenarioDefinition(
        id="basics_board",
        title="Read the Board",
        bootstrap=board_reading_bootstrap,
        steps=[
            TutorialStepDefinition(
                id="focus_owned_faction",
                objective_text="Left-click any highlighted Mountain faction object.",
                help_text="The ribbon, its territory, and the guidance button all count because the game treats them as the same faction focus.",
                allowed_actions={"select_faction", "inspect_hex", "inspect_faction"},
                highlights=[TutorialHighlightSpec("faction", "mountain")],
                completion_rule=_match_event("focus_faction", "faction", "mountain"),
            ),
            TutorialStepDefinition(
                id="focus_neutral_hex",
                objective_text="Left-click any highlighted neutral hex.",
                help_text="Neutral hexes are unclaimed territory that factions can later expand into.",
                allowed_actions={"inspect_hex"},
                highlights=[TutorialHighlightSpec("neutral_hexes", "all")],
                completion_rule=TutorialCompletionRule(
                    event_types={"inspect_hex"},
                    predicate=lambda event, scene: event.get("owner") is None,
                ),
            ),
            TutorialStepDefinition(
                id="focus_idol",
                objective_text="Left-click the highlighted idol token.",
                help_text="Idols stay on the map and score when the surrounding faction worships your spirit.",
                allowed_actions={"inspect_idol"},
                highlights=[TutorialHighlightSpec("idol_tokens", "all")],
                completion_rule=_rule("inspect_idol"),
            ),
        ],
        completion_summary="You can now read ownership, neutral space, and idols at a glance.",
    ),
    TutorialScenarioDefinition(
        id="basics_vagrant",
        title="Guide and Place an Idol",
        bootstrap=vagrant_guidance_bootstrap,
        steps=[
            TutorialStepDefinition(
                id="guide_mountain",
                objective_text="Left-click any highlighted Mountain faction object to choose it for guidance.",
                help_text="Any Mountain click that the game treats as selecting the faction will count here.",
                allowed_actions={"select_faction", "inspect_faction", "inspect_hex"},
                highlights=[TutorialHighlightSpec("faction", "mountain")],
                completion_rule=_match_event("focus_faction", "faction", "mountain"),
            ),
            TutorialStepDefinition(
                id="pick_battle_idol",
                objective_text="Left-click the highlighted Battle idol button.",
                help_text="This chooses which idol you are about to place on the map.",
                allowed_actions={"select_idol"},
                highlights=[TutorialHighlightSpec("idol_type", "battle")],
                completion_rule=_match_event("select_idol", "idol_type", "battle"),
                input_gate=_gate_equals("select_idol", "idol_type", "battle", "Battle idol button"),
            ),
            TutorialStepDefinition(
                id="place_battle_idol",
                objective_text="Left-click any highlighted neutral hex to place the idol.",
                help_text="Only neutral hexes can receive a new idol during this Era 1 guidance step.",
                allowed_actions={"select_hex"},
                highlights=[TutorialHighlightSpec("selectable_hexes", "idol")],
                completion_rule=TutorialCompletionRule(
                    event_types={"select_hex"},
                    predicate=lambda event, scene: event.get("kind") == "idol",
                ),
                input_gate=_gate_select_hex("idol", "neutral hexes"),
            ),
            TutorialStepDefinition(
                id="submit_guidance",
                objective_text="Left-click the highlighted Confirm button.",
                help_text="Confirm sends both the guidance choice and idol placement together.",
                allowed_actions={"submit"},
                highlights=[TutorialHighlightSpec("submit_button", "confirm")],
                completion_rule=_rule("vagrant_submitted"),
                requires_observation=True,
            ),
            TutorialStepDefinition(
                id="observe_guidance_result",
                objective_text="Watch the result, then left-click Continue.",
                help_text="Mountain is now guided by your spirit and starts Era 1 guidance with 3 Influence.",
                allowed_actions={"continue"},
                highlights=[TutorialHighlightSpec("faction", "mountain")],
                completion_rule=_rule("phase_result_applied"),
                requires_observation=True,
            ),
        ],
        completion_summary="Guidance begins with 3 Influence, and your idol is now in play.",
    ),
    TutorialScenarioDefinition(
        id="basics_trade",
        title="Draw and Choose Trade",
        bootstrap=trade_bootstrap,
        steps=[
            TutorialStepDefinition(
                id="pick_trade_card",
                objective_text="Left-click the highlighted Trade agenda card.",
                help_text="Guided factions draw extra choices, and Trade is the cleanest way to see gold and Regard gains.",
                allowed_actions={"select_agenda"},
                highlights=[TutorialHighlightSpec("agenda_type", "trade")],
                completion_rule=_match_event("select_agenda", "agenda", "trade"),
                input_gate=_gate_equals("select_agenda", "agenda", "trade", "Trade agenda card"),
            ),
            TutorialStepDefinition(
                id="submit_trade_card",
                objective_text="Left-click the highlighted Confirm button.",
                help_text="This locks in Trade for Mountain this turn.",
                allowed_actions={"submit"},
                highlights=[TutorialHighlightSpec("submit_button", "confirm")],
                completion_rule=_rule("agenda_submitted"),
                requires_observation=True,
            ),
            TutorialStepDefinition(
                id="observe_trade_result",
                objective_text="Watch the highlighted faction result, then left-click Continue.",
                help_text="Trade increases gold, can raise Regard, and your Influence ticks down after the turn resolves.",
                allowed_actions={"continue"},
                highlights=[TutorialHighlightSpec("faction", "mountain")],
                completion_rule=_rule("phase_result_applied"),
                requires_observation=True,
            ),
        ],
        completion_summary="You have seen guided agenda choice, trade income, regard gains, and influence decay.",
    ),
    TutorialScenarioDefinition(
        id="basics_expand",
        title="Expand Into New Territory",
        bootstrap=expand_bootstrap,
        steps=[
            TutorialStepDefinition(
                id="pick_expand_card",
                objective_text="Left-click the highlighted Expand agenda card.",
                help_text="Expand lets the guided faction claim neutral territory by paying gold.",
                allowed_actions={"select_agenda"},
                highlights=[TutorialHighlightSpec("agenda_type", "expand")],
                completion_rule=_match_event("select_agenda", "agenda", "expand"),
                input_gate=_gate_equals("select_agenda", "agenda", "expand", "Expand agenda card"),
            ),
            TutorialStepDefinition(
                id="submit_expand_card",
                objective_text="Left-click the highlighted Confirm button.",
                help_text="After you confirm Expand, the game asks for a target hex.",
                allowed_actions={"submit"},
                highlights=[TutorialHighlightSpec("submit_button", "confirm")],
                completion_rule=_rule("agenda_submitted"),
            ),
            TutorialStepDefinition(
                id="pick_expand_hex",
                objective_text="Left-click any highlighted neutral hex to choose Mountain's expansion target.",
                help_text="Only reachable neutral hexes are valid Expand targets.",
                allowed_actions={"select_hex"},
                highlights=[TutorialHighlightSpec("selectable_hexes", "expand")],
                completion_rule=_rule("expand_choice_selected"),
                input_gate=_gate_select_hex("expand", "expand targets"),
            ),
            TutorialStepDefinition(
                id="observe_expand_result",
                objective_text="Watch the territory change, then left-click Continue.",
                help_text="A successful Expand spends gold, adds territory, and builds toward Sprawl scoring.",
                allowed_actions={"continue"},
                highlights=[TutorialHighlightSpec("faction", "mountain")],
                completion_rule=_rule("phase_result_applied"),
                requires_observation=True,
            ),
        ],
        completion_summary="You have seen expansion cost, territorial growth, and Sprawl scoring pressure.",
    ),
    TutorialScenarioDefinition(
        id="basics_failed_expand",
        title="Failing Expand Still Matters",
        bootstrap=failed_expand_bootstrap,
        steps=[
            TutorialStepDefinition(
                id="pick_failed_expand_card",
                objective_text="Left-click the highlighted Expand agenda card.",
                help_text="This faction cannot afford a successful Expand right now, but the attempt still matters.",
                allowed_actions={"select_agenda"},
                highlights=[TutorialHighlightSpec("agenda_type", "expand")],
                completion_rule=_match_event("select_agenda", "agenda", "expand"),
                input_gate=_gate_equals("select_agenda", "agenda", "expand", "Expand agenda card"),
            ),
            TutorialStepDefinition(
                id="submit_failed_expand",
                objective_text="Left-click the highlighted Confirm button.",
                help_text="The failure fallback resolves after you confirm the Expand attempt.",
                allowed_actions={"submit"},
                highlights=[TutorialHighlightSpec("submit_button", "confirm")],
                completion_rule=_rule("agenda_submitted"),
                requires_observation=True,
            ),
            TutorialStepDefinition(
                id="observe_failed_expand_result",
                objective_text="Watch the result, then left-click Continue.",
                help_text="A failed Expand still grants bonus gold instead of doing nothing.",
                allowed_actions={"continue"},
                highlights=[TutorialHighlightSpec("faction", "mountain")],
                completion_rule=_rule("phase_result_applied"),
                requires_observation=True,
            ),
        ],
        completion_summary="You have seen the failed Expand gold bonus.",
    ),
    TutorialScenarioDefinition(
        id="basics_change",
        title="Permanent Change Modifiers",
        bootstrap=change_bootstrap,
        steps=[
            TutorialStepDefinition(
                id="pick_change_card",
                objective_text="Left-click the highlighted Change agenda card.",
                help_text="Change permanently upgrades one agenda type for this faction.",
                allowed_actions={"select_agenda"},
                highlights=[TutorialHighlightSpec("agenda_type", "change")],
                completion_rule=_match_event("select_agenda", "agenda", "change"),
                input_gate=_gate_equals("select_agenda", "agenda", "change", "Change agenda card"),
            ),
            TutorialStepDefinition(
                id="submit_change_card",
                objective_text="Left-click the highlighted Confirm button.",
                help_text="Confirming Change opens the modifier choice.",
                allowed_actions={"submit"},
                highlights=[TutorialHighlightSpec("submit_button", "confirm")],
                completion_rule=_rule("agenda_submitted"),
            ),
            TutorialStepDefinition(
                id="pick_change_modifier",
                objective_text="Left-click one of the highlighted modifier cards.",
                help_text="Each Change choice permanently strengthens that agenda type for Mountain.",
                allowed_actions={"select_change_card"},
                highlights=[TutorialHighlightSpec("change_cards", "all")],
                completion_rule=_rule("change_choice_selected"),
            ),
            TutorialStepDefinition(
                id="observe_change_result",
                objective_text="Watch the permanent modifier apply, then left-click Continue.",
                help_text="Future cards of that type now resolve with the upgraded effect.",
                allowed_actions={"continue"},
                highlights=[TutorialHighlightSpec("faction", "mountain")],
                completion_rule=_rule("phase_result_applied"),
                requires_observation=True,
            ),
        ],
        completion_summary="You have changed this faction's permanent agenda profile.",
    ),
    TutorialScenarioDefinition(
        id="basics_steal",
        title="Steal and Declare War",
        bootstrap=steal_war_bootstrap,
        steps=[
            TutorialStepDefinition(
                id="pick_steal_card",
                objective_text="Left-click the highlighted Steal agenda card.",
                help_text="Steal takes gold from neighbors and damages Regard at the same time.",
                allowed_actions={"select_agenda"},
                highlights=[TutorialHighlightSpec("agenda_type", "steal")],
                completion_rule=_match_event("select_agenda", "agenda", "steal"),
                input_gate=_gate_equals("select_agenda", "agenda", "steal", "Steal agenda card"),
            ),
            TutorialStepDefinition(
                id="submit_steal_card",
                objective_text="Left-click the highlighted Confirm button.",
                help_text="This Steal pushes Regard low enough to declare a War immediately.",
                allowed_actions={"submit"},
                highlights=[TutorialHighlightSpec("submit_button", "confirm")],
                completion_rule=_rule("agenda_submitted"),
                requires_observation=True,
            ),
            TutorialStepDefinition(
                id="observe_war_declared",
                objective_text="Watch the War declaration, then left-click Continue.",
                help_text="At -2 Regard or lower, Era 1 starts a War right away instead of waiting for a later turn.",
                allowed_actions={"continue"},
                highlights=[TutorialHighlightSpec("war", "active")],
                completion_rule=_rule("war_declared"),
                requires_observation=True,
            ),
        ],
        completion_summary="You have seen Steal, Regard damage, and War declaration.",
    ),
    TutorialScenarioDefinition(
        id="basics_war",
        title="War and Battle Scoring",
        bootstrap=war_scoring_bootstrap,
        steps=[
            TutorialStepDefinition(
                id="watch_war_resolution",
                objective_text="Watch the highlighted War arrows until the battle resolves.",
                help_text="In an unguided Era 1 War, both factions roll and add their territory count as power.",
                allowed_actions={"continue"},
                highlights=[TutorialHighlightSpec("war", "active")],
                completion_rule=_rule("war_resolved"),
                requires_observation=True,
            ),
            TutorialStepDefinition(
                id="watch_battle_scoring",
                objective_text="Watch the Battle idol scoring result, then left-click Continue.",
                help_text="Battle idols score when their surrounding faction wins Wars while worshipping your spirit.",
                allowed_actions={"continue"},
                highlights=[TutorialHighlightSpec("idol_tokens", "all")],
                completion_rule=_rule("vp_scored"),
                requires_observation=True,
            ),
        ],
        completion_summary="You have seen immediate war resolution and Battle idol scoring.",
    ),
    TutorialScenarioDefinition(
        id="basics_worship",
        title="Worship Drives Scoring",
        bootstrap=worship_scoring_bootstrap,
        steps=[
            TutorialStepDefinition(
                id="focus_scoring_faction",
                objective_text="Left-click any highlighted Mountain faction object.",
                help_text="This opens the faction details while scoring is resolving around it.",
                allowed_actions={"select_faction", "inspect_faction", "inspect_hex"},
                highlights=[TutorialHighlightSpec("faction", "mountain")],
                completion_rule=_match_event("focus_faction", "faction", "mountain"),
            ),
            TutorialStepDefinition(
                id="watch_worship_scoring",
                objective_text="Watch the scoring summary, then left-click Continue.",
                help_text="Battle, Affluence, and Sprawl idols all pay out because Mountain worships your spirit.",
                allowed_actions={"continue"},
                highlights=[
                    TutorialHighlightSpec("panel_counter", "worship"),
                    TutorialHighlightSpec("idol_tokens", "all"),
                ],
                completion_rule=_rule("phase_result_applied"),
                requires_observation=True,
            ),
        ],
        completion_summary="You have seen why Worship is the bridge between idols and VP.",
    ),
]


ADVANCED_SCENARIOS = [
    TutorialScenarioDefinition(
        id="advanced_contested",
        title="Contested Guidance",
        bootstrap=contested_guidance_bootstrap,
        steps=[
            TutorialStepDefinition(
                id="target_contested_faction",
                objective_text="Left-click any highlighted Mountain faction object.",
                help_text="A rival spirit is scripted to choose the same faction this turn.",
                allowed_actions={"select_faction", "inspect_faction", "inspect_hex"},
                highlights=[TutorialHighlightSpec("faction", "mountain")],
                completion_rule=_match_event("focus_faction", "faction", "mountain"),
            ),
            TutorialStepDefinition(
                id="submit_contested_guidance",
                objective_text="Left-click the highlighted Confirm button.",
                help_text="Both spirits now collide on Mountain, producing contested guidance.",
                allowed_actions={"submit"},
                highlights=[TutorialHighlightSpec("submit_button", "confirm")],
                completion_rule=_rule("vagrant_submitted"),
                requires_observation=True,
            ),
            TutorialStepDefinition(
                id="observe_contested_result",
                objective_text="Watch the contested guidance result, then left-click Continue.",
                help_text="No one guides the faction this turn, and that faction is blocked next Vagrant phase.",
                allowed_actions={"continue"},
                highlights=[TutorialHighlightSpec("faction", "mountain")],
                completion_rule=_rule("guide_contested"),
                requires_observation=True,
            ),
        ],
        completion_summary="You have seen contested guidance and the one-turn faction cooldown.",
    ),
    TutorialScenarioDefinition(
        id="advanced_worship_timing",
        title="Worship Restrictions and Theft",
        bootstrap=worship_timing_bootstrap,
        steps=[
            TutorialStepDefinition(
                id="pick_worship_target",
                objective_text="Left-click any highlighted Mountain faction object.",
                help_text="This faction already worships another spirit, so the tutorial can show the worship tie-break rules.",
                allowed_actions={"select_faction", "inspect_faction", "inspect_hex"},
                highlights=[TutorialHighlightSpec("faction", "mountain")],
                completion_rule=_match_event("focus_faction", "faction", "mountain"),
            ),
            TutorialStepDefinition(
                id="submit_worship_challenge",
                objective_text="Left-click the highlighted Confirm button.",
                help_text="Guidance starts the worship comparison immediately.",
                allowed_actions={"submit"},
                highlights=[TutorialHighlightSpec("submit_button", "confirm")],
                completion_rule=_rule("vagrant_submitted"),
                requires_observation=True,
            ),
            TutorialStepDefinition(
                id="observe_worship_shift",
                objective_text="Watch the worship change, then left-click Continue.",
                help_text="When idol counts tie, the currently guiding spirit wins the worship tie-break.",
                allowed_actions={"continue"},
                highlights=[TutorialHighlightSpec("panel_counter", "worship")],
                completion_rule=_rule("worship_replaced"),
                requires_observation=True,
            ),
        ],
        completion_summary="You have seen Worship restrictions and the timing of Worship theft.",
    ),
    TutorialScenarioDefinition(
        id="advanced_ejection",
        title="Ejection at Zero Influence",
        bootstrap=ejection_bootstrap,
        steps=[
            TutorialStepDefinition(
                id="pick_removed_agenda",
                objective_text="Left-click any highlighted agenda under Remove.",
                help_text="Zero Influence ejects your spirit and forces one agenda out of the faction pool.",
                allowed_actions={"select_ejection_remove"},
                highlights=[
                    TutorialHighlightSpec("panel_counter", "influence"),
                    TutorialHighlightSpec("ejection_remove_buttons", "all"),
                ],
                completion_rule=_rule("ejection_remove_selected"),
            ),
            TutorialStepDefinition(
                id="pick_added_agenda",
                objective_text="Left-click any highlighted agenda under Add.",
                help_text="This is the new agenda type that replaces the removed one in the pool.",
                allowed_actions={"select_ejection_add"},
                highlights=[TutorialHighlightSpec("ejection_add_buttons", "all")],
                completion_rule=_rule("ejection_add_selected"),
            ),
            TutorialStepDefinition(
                id="submit_ejection_choice",
                objective_text="Left-click the highlighted Confirm button.",
                help_text="Confirm finalizes the pool swap and ends your guidance.",
                allowed_actions={"submit"},
                highlights=[TutorialHighlightSpec("submit_button", "confirm")],
                completion_rule=_rule("ejection_submitted"),
                requires_observation=True,
            ),
            TutorialStepDefinition(
                id="observe_ejection_result",
                objective_text="Watch the ejection result, then left-click Continue.",
                help_text="Your spirit becomes Vagrant again after the agenda pool update.",
                allowed_actions={"continue"},
                highlights=[TutorialHighlightSpec("panel_counter", "guidance")],
                completion_rule=_rule("ejected"),
                requires_observation=True,
            ),
        ],
        completion_summary="You have seen the full ejection flow.",
    ),
    TutorialScenarioDefinition(
        id="advanced_winner_choice",
        title="Guided Winner Choice",
        bootstrap=winner_choice_bootstrap,
        steps=[
            TutorialStepDefinition(
                id="pick_guided_winner",
                objective_text="Left-click one of the highlighted winner buttons.",
                help_text="Because only one side is guided, you choose the winner directly.",
                allowed_actions={"select_winner"},
                highlights=[TutorialHighlightSpec("winner_choices", "all")],
                completion_rule=_rule("winner_choice_selected"),
            ),
            TutorialStepDefinition(
                id="submit_guided_winner",
                objective_text="Left-click the highlighted Confirm button.",
                help_text="This locks in your chosen winner for the war.",
                allowed_actions={"submit"},
                highlights=[TutorialHighlightSpec("submit_button", "confirm")],
                completion_rule=_rule("winner_choice_submitted"),
                requires_observation=True,
            ),
            TutorialStepDefinition(
                id="observe_guided_winner_result",
                objective_text="Watch the war resolve, then left-click Continue.",
                help_text="No dice roll is needed when exactly one side is guided and you pick the winner.",
                allowed_actions={"continue"},
                highlights=[TutorialHighlightSpec("war", "active")],
                completion_rule=_rule("war_resolved"),
                requires_observation=True,
            ),
        ],
        completion_summary="You have seen direct war-outcome control from guidance.",
    ),
    TutorialScenarioDefinition(
        id="advanced_spoils",
        title="Batched Spoils of War",
        bootstrap=spoils_choice_bootstrap,
        steps=[
            TutorialStepDefinition(
                id="pick_batched_spoils",
                objective_text="Left-click one highlighted spoils card under each defeated faction.",
                help_text="Each victory needs its own spoils pick before anything resolves.",
                allowed_actions={"select_spoils_card"},
                highlights=[TutorialHighlightSpec("spoils_cards", "all")],
                completion_rule=_rule("spoils_choice_selected"),
            ),
            TutorialStepDefinition(
                id="submit_batched_spoils",
                objective_text="Left-click the highlighted Confirm button.",
                help_text="This resolves the whole batch of guided spoils picks together.",
                allowed_actions={"submit"},
                highlights=[TutorialHighlightSpec("submit_button", "confirm")],
                completion_rule=_rule("spoils_choice_submitted"),
                requires_observation=True,
            ),
            TutorialStepDefinition(
                id="observe_batched_spoils",
                objective_text="Watch the spoils resolve, then left-click Continue.",
                help_text="Guided spoils are chosen first and only then resolved into their individual effects.",
                allowed_actions={"continue"},
                highlights=[TutorialHighlightSpec("faction", "mountain")],
                completion_rule=_rule("phase_result_applied"),
                requires_observation=True,
            ),
        ],
        completion_summary="You have seen multi-pick spoils resolution.",
    ),
    TutorialScenarioDefinition(
        id="advanced_spoils_change",
        title="Spoils Change Follow-Up",
        bootstrap=spoils_change_bootstrap,
        steps=[
            TutorialStepDefinition(
                id="pick_spoils_change_modifier",
                objective_text="Left-click one highlighted spoils Change card.",
                help_text="Spoils Change opens its own modifier choice instead of resolving immediately.",
                allowed_actions={"select_spoils_change_card"},
                highlights=[TutorialHighlightSpec("spoils_change_cards", "all")],
                completion_rule=_rule("spoils_change_selected"),
            ),
            TutorialStepDefinition(
                id="submit_spoils_change_modifier",
                objective_text="Left-click the highlighted Confirm button.",
                help_text="This finalizes the modifier gained from the spoils reward.",
                allowed_actions={"submit"},
                highlights=[TutorialHighlightSpec("submit_button", "confirm")],
                completion_rule=_rule("spoils_change_submitted"),
                requires_observation=True,
            ),
            TutorialStepDefinition(
                id="observe_spoils_change_result",
                objective_text="Watch the permanent modifier apply, then left-click Continue.",
                help_text="The spoils reward has now turned into a permanent faction upgrade.",
                allowed_actions={"continue"},
                highlights=[TutorialHighlightSpec("faction", "mountain")],
                completion_rule=_rule("phase_result_applied"),
                requires_observation=True,
            ),
        ],
        completion_summary="You have seen the spoils Change branch.",
    ),
    TutorialScenarioDefinition(
        id="advanced_spoils_expand",
        title="Spoils Expand Follow-Up",
        bootstrap=spoils_expand_bootstrap,
        steps=[
            TutorialStepDefinition(
                id="pick_spoils_expand_hex",
                objective_text="Left-click one highlighted enemy hex.",
                help_text="Spoils Expand takes territory from the defeated faction instead of claiming neutral land.",
                allowed_actions={"select_hex"},
                highlights=[TutorialHighlightSpec("selectable_hexes", "spoils_expand")],
                completion_rule=_rule("spoils_expand_choice_selected"),
                input_gate=_gate_select_hex("spoils_expand", "enemy hexes"),
            ),
            TutorialStepDefinition(
                id="submit_spoils_expand_hex",
                objective_text="Left-click the highlighted Confirm button.",
                help_text="This submits the conquest target for the spoils Expand.",
                allowed_actions={"submit"},
                highlights=[TutorialHighlightSpec("submit_button", "confirm")],
                completion_rule=_rule("spoils_expand_submitted"),
                requires_observation=True,
            ),
            TutorialStepDefinition(
                id="observe_spoils_expand_result",
                objective_text="Watch the territory change, then left-click Continue.",
                help_text="The spoils Expand has now conquered one of the loser's hexes.",
                allowed_actions={"continue"},
                highlights=[TutorialHighlightSpec("faction", "mountain")],
                completion_rule=_rule("phase_result_applied"),
                requires_observation=True,
            ),
        ],
        completion_summary="You have seen the spoils Expand branch.",
    ),
    TutorialScenarioDefinition(
        id="advanced_respawn",
        title="Faction Respawn",
        bootstrap=respawn_bootstrap,
        steps=[
            TutorialStepDefinition(
                id="pick_respawn_target",
                objective_text="Left-click one highlighted neutral hex.",
                help_text="A destroyed faction must respawn on a neutral hex at the end of the turn.",
                allowed_actions={"select_hex"},
                highlights=[TutorialHighlightSpec("selectable_hexes", "respawn")],
                completion_rule=_rule("respawn_choice_selected"),
                input_gate=_gate_select_hex("respawn", "respawn hexes"),
            ),
            TutorialStepDefinition(
                id="submit_respawn_target",
                objective_text="Left-click the highlighted Confirm button.",
                help_text="This locks in the respawn location.",
                allowed_actions={"submit"},
                highlights=[TutorialHighlightSpec("submit_button", "confirm")],
                completion_rule=_rule("respawn_choice_submitted"),
                requires_observation=True,
            ),
            TutorialStepDefinition(
                id="observe_respawn_result",
                objective_text="Watch the faction respawn, then left-click Continue.",
                help_text="Its gold resets as part of the respawn process before it re-enters the map.",
                allowed_actions={"continue"},
                highlights=[TutorialHighlightSpec("faction", "mountain")],
                completion_rule=_rule("faction_respawned"),
                requires_observation=True,
            ),
        ],
        completion_summary="You have seen guided faction respawn and the gold reset.",
    ),
    TutorialScenarioDefinition(
        id="advanced_unguided",
        title="Unguided Expand Preference",
        bootstrap=unguided_behavior_bootstrap,
        steps=[
            TutorialStepDefinition(
                id="focus_unguided_faction",
                objective_text="Left-click any highlighted Plains faction object.",
                help_text="This is the faction that resolves an unguided Expand on its own.",
                allowed_actions={"select_faction", "inspect_faction", "inspect_hex"},
                highlights=[TutorialHighlightSpec("faction", "plains")],
                completion_rule=_match_event("focus_faction", "faction", "plains"),
            ),
            TutorialStepDefinition(
                id="watch_unguided_expand_choice",
                objective_text="Watch the unguided Expand choose the idol hex, then left-click Continue.",
                help_text="Unguided behavior is random overall, but idol-bearing hexes are preferred when available.",
                allowed_actions={"continue"},
                highlights=[
                    TutorialHighlightSpec("faction", "plains"),
                    TutorialHighlightSpec("idol_tokens", "all"),
                ],
                completion_rule=_rule("phase_result_applied"),
                requires_observation=True,
            ),
        ],
        completion_summary="You have seen unguided behavior and idol-target preference.",
    ),
]
